# Generated by Django 4.2.1 on 2023-06-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_is_active_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
    ]
